### ISSUE TITLE
`jug.init` does not work without extensions

### ISSUE THREAD

**Issue by QuLogic** [luispedro/jug#20]
When trying the examples, e.g., `examples/decrypt/printjugresults.py`:
```python
$ python3 printjugresults.py 
Traceback (most recent call last):
  File "printjugresults.py", line 2, in <module>
    jug.init('jugfile', 'jugdata')
  File ".../lib/python3.4/site-packages/jug/jug.py", line 386, in init
    jugfile_contents = open(jugfile).read()
FileNotFoundError: [Errno 2] No such file or directory: 'jugfile'
```
So I change the `jug.init` call to use `jugfile.py` instead:
```python
$ python3 printjugresults.py 
Traceback (most recent call last):
  File "printjugresults.py", line 4, in <module>
    results = jug.task.value(jugfile.fullresults)
  File ".../lib/python3.4/site-packages/jug/task.py", line 446, in value
    return elem.value()
  File ".../lib/python3.4/site-packages/jug/task.py", line 111, in value
    return self.result
  File ".../lib/python3.4/site-packages/jug/task.py", line 106, in _get_result
    if not hasattr(self, '_result'): self.load()
  File ".../lib/python3.4/site-packages/jug/task.py", line 147, in load
    assert self.can_load()
AssertionError
```
Then I change `jug.init` to also use `jugfile.jugdata`, and:
```bash
$ python3 printjugresults.py 
Jug is perfect for embarassingly parallel applications.
    -- Luis Pedro Coelho

    Password was 'qwert'
```

According to the documentation, the full names should not be necessary, but that does not seem to be the case.

**Comment by luispedro** [comment]
Somehow, I managed to not notice this issue until now. I will fix it in a second.

Thank you very much for the report.

**Comment by QuLogic** [comment]
The examples also need updating to account for this difference.

**Comment by luispedro** [comment]
Thanks again. I will fix that too...
