### ISSUE TITLE
`RuntimeError: maximum recursion depth exceeded while calling a Python object`

### ISSUE THREAD

**Issue by samuela** [luispedro/jug#30]
Came across this error today: 

```
CRITICAL:root:Exception while running tangent_lstm.test_lstm: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/gpfs/main/home/skainswo/Research/kaggle_gal/venv/bin/jug", line 5, in <module>
    main()
  File "/gpfs/main/home/skainswo/Research/kaggle_gal/venv/local/lib/python2.7/site-packages/jug/jug.py", line 415, in main
    execute(options)
  File "/gpfs/main/home/skainswo/Research/kaggle_gal/venv/local/lib/python2.7/site-packages/jug/jug.py", line 254, in execute
    execution_loop(tasks, options)
  File "/gpfs/main/home/skainswo/Research/kaggle_gal/venv/local/lib/python2.7/site-packages/jug/jug.py", line 163, in execution_loop
    t.run(debug_mode=options.debug)
  File "/gpfs/main/home/skainswo/Research/kaggle_gal/venv/local/lib/python2.7/site-packages/jug/task.py", line 95, in run
    self.store.dump(self._result, name)
  File "/gpfs/main/home/skainswo/Research/kaggle_gal/venv/local/lib/python2.7/site-packages/jug/backends/file_store.py", line 139, in dump
    encode_to(object, output)
  File "/gpfs/main/home/skainswo/Research/kaggle_gal/venv/local/lib/python2.7/site-packages/jug/backends/encode.py", line 77, in encode_to
    write(object, stream)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

I'm getting this error when creating a Task that wraps a function which returns a Keras model.

**Comment by luispedro** [comment]
Can you perhaps post a small example?

Maybe Keras' models are not pickle()able?

**Comment by samuela** [comment]
Unfortunately, I can reproduce the error in my own messy code but I'm having trouble coming up with a simple example.

**Comment by luispedro** [comment]
Is the output of the task pickle()able (i.e., can you call ``pickle.dump`` on it)? If not, then that is your issue (we can discuss ways of working around it, too).

If it can be pickled, then there may be something else.

**Comment by samuela** [comment]
I'll check if it's pickle()able. My guess is that it is in fact but I'm not sure. I'm sorry this is such a vague issue. It's pretty tricky to reproduce I'm afraid.

**Comment by luispedro** [comment]
Since it's not clear whether this report is still valid, I'm closing. Please reopen if you have more info/update.
