### ISSUE TITLE
"SystemError: error return without exception set"

### ISSUE THREAD

**Issue by samuela** [luispedro/jug#32]
Ok, so take for example

```python
def _buildXY():
  tan_train = [Task(np.random.randn, 100000, 528) for i in range(7)]
  tan_test = [Task(np.random.randn, 100000, 528) for i in range(5)]

  # xs, ys - lists of arrays
  def pad(xs, ys):
    maxT = max( x.shape[0] for x in xs )
    x = np.zeros((len(xs), maxT, xs[0].shape[1]))
    y = np.zeros((len(ys), maxT, ys[0].shape[1]))
    for ii in xrange(len(xs)): 
      t = xs[ii].shape[0]
      x[ii,:t,:] = xs[ii]
      y[ii,:t,:] = ys[ii]
    return x, y

  y_train = [np.random.randn(100000, 5) for i in range(7)]
  y_test = [np.random.randn(100000, 5) for i in range(5)]

  train = Task(pad, tan_train, y_train)
  test = Task(pad, tan_test, y_test)

  return train[0], train[1], test[0], test[1]

_buildXY()
```

Running `jug execute` gives me the error:

```
CRITICAL:root:Exception while running tangent_lstm.pad: error return without exception set
Traceback (most recent call last):
  File "/gpfs/main/home/skainswo/Research/kaggle_gal/venv/bin/jug", line 5, in <module>
    main()
  File "/gpfs/main/home/skainswo/Research/kaggle_gal/venv/local/lib/python2.7/site-packages/jug/jug.py", line 415, in main
    execute(options)
  File "/gpfs/main/home/skainswo/Research/kaggle_gal/venv/local/lib/python2.7/site-packages/jug/jug.py", line 254, in execute
    execution_loop(tasks, options)
  File "/gpfs/main/home/skainswo/Research/kaggle_gal/venv/local/lib/python2.7/site-packages/jug/jug.py", line 163, in execution_loop
    t.run(debug_mode=options.debug)
  File "/gpfs/main/home/skainswo/Research/kaggle_gal/venv/local/lib/python2.7/site-packages/jug/task.py", line 95, in run
    self.store.dump(self._result, name)
  File "/gpfs/main/home/skainswo/Research/kaggle_gal/venv/local/lib/python2.7/site-packages/jug/backends/file_store.py", line 139, in dump
    encode_to(object, output)
  File "/gpfs/main/home/skainswo/Research/kaggle_gal/venv/local/lib/python2.7/site-packages/jug/backends/encode.py", line 77, in encode_to
    write(object, stream)
SystemError: error return without exception set
```

**Comment by luispedro** [comment]
Ok, this was a fun one, it's not every day you run into a bona fide *bug in the language interpreter*.

It seems like it's a Python issue that has been fixed in newer versions of Python: https://github.com/numpy/numpy/issues/2396

Indeed on my machine, it gives me your error on 2.7 but works on 3.4, albeit consuming a lot of memory.

As an alternative to upgrading Python, if you can adapt the code, you might consider returning a single array at a time as numpy arrays are just saved as arrays on disk in numpy format.

**Comment by luispedro** [comment]
Given the above analysis, I think I am closing this as a jug issue. The fundamental problem was a Python bug and I would consider a patch with a jug workaround, but, at the moment, it's not a priority.

**Comment by samuela** [comment]
@luispedro Great, thanks for the info! I'm amazed that this ended up being such a complicated issue.
