### ISSUE TITLE
Error while running jug execute prime.py

### ISSUE THREAD

**Issue by deepakagrawal** [luispedro/jug#72]
I tried the default example given in the documents. I get the following error. Can you please help me

```
Traceback (most recent call last):
  File "/storage/work/dua143/anaconda2/bin/jug", line 11, in <module>
    sys.exit(main())
  File "/storage/work/dua143/anaconda2/lib/python2.7/site-packages/jug/jug.py", line 278, in main
    cmdapi.run(options.subcommand, options=options, store=store, jugspace=jugspace)
  File "/storage/work/dua143/anaconda2/lib/python2.7/site-packages/jug/subcommands/__init__.py", line 271, in run
    return cmd(*args, **kwargs)
  File "/storage/work/dua143/anaconda2/lib/python2.7/site-packages/jug/subcommands/__init__.py", line 161, in __call__
    return self.run(*args, **kwargs)
  File "/storage/work/dua143/anaconda2/lib/python2.7/site-packages/jug/subcommands/execute.py", line 86, in run
    store, jugspace = init(options.jugfile, options.jugdir, store=store)
  File "/storage/work/dua143/anaconda2/lib/python2.7/site-packages/jug/jug.py", line 97, in init
    jugfile_contents = open(jugfile).read()
IOError: [Errno 2] No such file or directory: 'primes.py'

```

**Comment by luispedro** [comment]
According to the error message, `primes.py` was not found, while the example expects that you have saved the code to a file called `primes.py`

You can download it here: https://github.com/luispedro/jug/tree/master/examples/primes
